"""Deutsch (App) -> Englisch (openfootball) für Ergebnis-Sync."""

from __future__ import annotations

TEAM_DE_TO_EN: dict[str, str] = {
    "Mexiko": "Mexico",
    "Südafrika": "South Africa",
    "Südkorea": "South Korea",
    "Tschechien": "Czech Republic",
    "Kanada": "Canada",
    "Bosnien und Herzegowina": "Bosnia & Herzegovina",
    "Katar": "Qatar",
    "Schweiz": "Switzerland",
    "Brasilien": "Brazil",
    "Marokko": "Morocco",
    "Haiti": "Haiti",
    "Schottland": "Scotland",
    "USA": "USA",
    "Paraguay": "Paraguay",
    "Australien": "Australia",
    "Türkei": "Turkey",
    "Deutschland": "Germany",
    "Curaçao": "Curaçao",
    "Elfenbeinküste": "Ivory Coast",
    "Ecuador": "Ecuador",
    "Niederlande": "Netherlands",
    "Japan": "Japan",
    "Schweden": "Sweden",
    "Tunesien": "Tunisia",
    "Belgien": "Belgium",
    "Ägypten": "Egypt",
    "Iran": "Iran",
    "Neuseeland": "New Zealand",
    "Spanien": "Spain",
    "Kap Verde": "Cape Verde",
    "Saudi-Arabien": "Saudi Arabia",
    "Uruguay": "Uruguay",
    "Frankreich": "France",
    "Senegal": "Senegal",
    "Irak": "Iraq",
    "Norwegen": "Norway",
    "Argentinien": "Argentina",
    "Algerien": "Algeria",
    "Österreich": "Austria",
    "Jordanien": "Jordan",
    "Portugal": "Portugal",
    "DR Kongo": "DR Congo",
    "Usbekistan": "Uzbekistan",
    "Kolumbien": "Colombia",
    "England": "England",
    "Kroatien": "Croatia",
    "Ghana": "Ghana",
    "Panama": "Panama",
}

OPENFOOTBALL_TEAM_NAMES = {en: de for de, en in TEAM_DE_TO_EN.items()}
